---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

# Times que levaram mais goleadas de 2003 a 2023

*Passe o mouse em cima das bolinhas para ver o placar.*

```{r}
tab_goleadas <- readr::read_rds("tab_goleadas.rds")

top_20 <- tab_goleadas |>
  dplyr::count(perdedor) |>
  dplyr::slice_max(order_by = n, n = 20)

tab_grafico <- tab_goleadas |>
  dplyr::select(
    perdedor,
    date,
    home,
    score,
    away
  ) |>
  dplyr::group_by(perdedor) |>
  dplyr::mutate(
    contagem = dplyr::row_number(),
    placar = glue::glue(
      "{home} {score} {away}"
    ),
    n = max(contagem),
    date = format(date, "%d/%m/%Y"),
    serie = perdedor
  ) |>
  dplyr::ungroup() |>
  dplyr::arrange(n, perdedor, date) |>
  dplyr::semi_join(
    top_20,
    by = "perdedor"
  ) |>
  dplyr::left_join(
    dplyr::select(brasileirao::teams, team, cor = color1),
    by = c("perdedor" = "team")
  ) |>
  dplyr::select(
    serie,
    cor,
    contagem,
    perdedor,
    date,
    placar
  ) |>
  tidyr::nest(data = -c(serie, cor)) |>
  dplyr::mutate(
    cor = dplyr::case_when(
      serie == "Vasco da Gama" ~ "#000000",
      serie == "Flamengo" ~ "#b92218",
      serie == "Athletico PR" ~ "#a50e15",
      serie == "Fluminense" ~ "#7a0423",
      serie == "Ponte Preta" ~ "#000000",
      serie == "Ponte Preta" ~ "#d1171f",
      serie == "Corinthians" ~ "#000000",
      serie == "Vitória" ~ "#f70f02",
      serie == "São Paulo" ~ "#cd0a12",
      serie == "Bahia" ~ "#2367a8",
      TRUE ~ cor
    )
  )

echarts4r::e_charts() |>
  echarts4r::e_list(
    list(
      xAxis = list(
        type = "value"
      ),
      yAxis = list(
        type = "category"
      ),
      series = purrr::map(
        tab_grafico$serie,
        ~ list(
          type = "scatter",
          data = tab_grafico |>
            dplyr::filter(serie == .x) |>
            tidyr::unnest(cols = data) |>
            dplyr::select(-serie, -cor) |>
            unname() |>
            purrr::transpose()
        )
      ),
      tooltip = list(
        show = TRUE,
        formatter = htmlwidgets::JS(
          "function(params) {
            var text = params.value[2] + '<br>';
            text += params.value[3];
            return text;
          }
          "
        )
      ),
      color = tab_grafico$cor,
      grid = list(
        containLabel = TRUE
      )
    )
  )

```

> Critério: placares com diferença de 3 gols ou mais foram considerados goeladas.

---

Feito por [William Amorim](https://twitter.com/wamorim_) na 16a Amostra de Estatística do IME-USP.

